service: currency-converter # NOTE: Don't put the word "google" in here

provider:
  name: google
  stage: dev
  runtime: python37
  memorySize: 128
  region: europe-west1
  project: currency-converter-245112
  # The GCF credentials can be a little tricky to set up. Luckily we've documented this for you here:
  # https://serverless.com/framework/docs/providers/google/guide/credentials/
  #
  # the path to the credentials file needs to be absolute
  credentials: /Users/lekke/.gcloud/currency-converter-245112.json

plugins:
  - serverless-google-cloudfunctions

# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  first:
    handler: http
    events:
      - http: path
    environment:
      KEY_RING_ID: 'key-ring-1'
      KEY_ID: 'key-1'
      # Set API key for this cloud function
      # & encrypt it
      API_KEY_ENCRYPTED_BASE64: 'CiQAu1AJUl9dZNO64REnQgM0bWfIpt32sBe5l7iyT5uMbSLyxlkSMQD3jYcEU1Pn8WTvcQHPkGu2tcq05L6qa6iM1qzfho8CwbUvBdztfXB/IG2mazGqrNk='
      # Get API key by registering at https://free.currencyconverterapi.com/
      # & encrypt it
      API_KEY_CURRENCY_CONVERTER_ENCRYPTED_BASE64: 'CiQAu1AJUoxc1cjB3aSwesMzXqKmdaHGEUAu3Fm1e/RmICWfz/YSPQD3jYcEpXK3NKN2iDoVqwBdJtyzya4vsbvwXmgF6w2l791iXDuE3x1bGVsk4Q6Krck0muh2beep2mKXgzE='
      # Get secret for Approov by running Approov CLI tool ´approov secret administration.tok -get'
      # & encrypt it
      APPROOV_SECRET_ENCRYPTED_BASE64: 'CiQAu1AJUtZO6p2lyf9t5qQUE14KJ1Ph4x9VwkcNrA4Ya4C6BEUSgQEA942HBH8wBTVkC8eUouX/fAv/uxk810/B6k27KX1vd8zySj7oZOI3eizcZR2qGNGsKYf89RYt9EPbCCcoOLAscp6rLA7fNApkFRlADh2hROTJkAuCDC89III3ihbB+HvcOMiGZSgcQVCL/6AWcHvS8j0P4ougaMXLtueDIRpfVCI='
